# Manté al dia les accions de GitHub fixades per commit.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "Accions"
